### ISSUE TITLE
SVG viewBox attribute is not respected

### ISSUE THREAD

**Issue by btel** [btel/svg_utils#1]
http://www.w3.org/TR/SVG/coords.html#ViewBoxAttribute

**Comment by btel** [comment]
fixed by commit b15be5e35c7bf9b068b881d68f3b0a86f0081628

**Comment by ErickMR19** [comment]
SVG viewBox attribute is still not respected.

[viewBox values](https://www.w3.org/TR/SVG/coords.html#ViewBoxAttribute) are [numbers](https://www.w3.org/TR/css3-values/#numbers), with no units, no [dimensions](https://www.w3.org/TR/css3-values/#dimension)

Already fixed in #27
